[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "instrument"
path = "src/instrument.rs"

[[bin]]
name = "strip"
path = "src/strip.rs"

[[bin]]
name = "cli_dbg"
path = "src/cli_dbg.rs"